"""
Multi-Target Transpiler for QMoosa-PQ.
Compiles QuantumAST to:
1. Qiskit Python Code & OpenQASM 3.0 (IBM Quantum ecosystem)
2. Origin Pilot / QPanda QRunes (Origin Quantum OS)
"""

from .ast_circuit import QuantumAST, GateType, GateNode


class QiskitTranspiler:
    """Compiles AST to Qiskit Python code and executable scripts."""

    @staticmethod
    def transpile(ast: QuantumAST) -> str:
        lines = [
            "# Generated by QMoosa-PQ Autonomous Synthesis Engine",
            "from qiskit import QuantumCircuit",
            "",
            f"def build_circuit() -> QuantumCircuit:",
            f'    qc = QuantumCircuit({ast.num_qubits}, {ast.num_clbits}, name="{ast.name}")',
            "",
        ]

        for gate in ast.gates:
            gt = gate.gate_type
            if gt == GateType.H:
                lines.append(f"    qc.h({gate.targets[0]})")
            elif gt == GateType.X:
                lines.append(f"    qc.x({gate.targets[0]})")
            elif gt == GateType.Y:
                lines.append(f"    qc.y({gate.targets[0]})")
            elif gt == GateType.Z:
                lines.append(f"    qc.z({gate.targets[0]})")
            elif gt == GateType.S:
                lines.append(f"    qc.s({gate.targets[0]})")
            elif gt == GateType.T:
                lines.append(f"    qc.t({gate.targets[0]})")
            elif gt == GateType.RX:
                lines.append(f"    qc.rx({gate.params[0]:.4f}, {gate.targets[0]})")
            elif gt == GateType.RY:
                lines.append(f"    qc.ry({gate.params[0]:.4f}, {gate.targets[0]})")
            elif gt == GateType.RZ:
                lines.append(f"    qc.rz({gate.params[0]:.4f}, {gate.targets[0]})")
            elif gt == GateType.PHASE:
                lines.append(f"    qc.p({gate.params[0]:.4f}, {gate.targets[0]})")
            elif gt == GateType.CX:
                lines.append(f"    qc.cx({gate.controls[0]}, {gate.targets[0]})")
            elif gt == GateType.CZ:
                lines.append(f"    qc.cz({gate.controls[0]}, {gate.targets[0]})")
            elif gt == GateType.SWAP:
                lines.append(f"    qc.swap({gate.targets[0]}, {gate.targets[1]})")
            elif gt == GateType.BARRIER:
                lines.append("    qc.barrier()")
            elif gt == GateType.MEASURE:
                c_idx = gate.classical_target if gate.classical_target is not None else gate.targets[0]
                lines.append(f"    qc.measure({gate.targets[0]}, {c_idx})")
            elif gt == GateType.ORACLE:
                lines.append(f'    # Oracle block: {gate.label} on qubits {gate.targets}')

        lines.extend([
            "",
            "    return qc",
            "",
            "if __name__ == '__main__':",
            "    circuit = build_circuit()",
            "    print(circuit.draw(output='text'))",
        ])
        return "\n".join(lines)


class OpenQASMTranspiler:
    """Compiles AST to standard OpenQASM 3.0 format."""

    @staticmethod
    def transpile(ast: QuantumAST) -> str:
        lines = [
            "OPENQASM 3.0;",
            'include "stdgates.inc";',
            "",
            f"qubit[{ast.num_qubits}] q;",
        ]
        if ast.num_clbits > 0:
            lines.append(f"bit[{ast.num_clbits}] c;")

        lines.append("")

        for gate in ast.gates:
            gt = gate.gate_type
            if gt == GateType.H:
                lines.append(f"h q[{gate.targets[0]}];")
            elif gt == GateType.X:
                lines.append(f"x q[{gate.targets[0]}];")
            elif gt == GateType.Y:
                lines.append(f"y q[{gate.targets[0]}];")
            elif gt == GateType.Z:
                lines.append(f"z q[{gate.targets[0]}];")
            elif gt == GateType.S:
                lines.append(f"s q[{gate.targets[0]}];")
            elif gt == GateType.T:
                lines.append(f"t q[{gate.targets[0]}];")
            elif gt == GateType.RX:
                lines.append(f"rx({gate.params[0]:.4f}) q[{gate.targets[0]}];")
            elif gt == GateType.RY:
                lines.append(f"ry({gate.params[0]:.4f}) q[{gate.targets[0]}];")
            elif gt == GateType.RZ:
                lines.append(f"rz({gate.params[0]:.4f}) q[{gate.targets[0]}];")
            elif gt == GateType.PHASE:
                lines.append(f"phase({gate.params[0]:.4f}) q[{gate.targets[0]}];")
            elif gt == GateType.CX:
                lines.append(f"cx q[{gate.controls[0]}], q[{gate.targets[0]}];")
            elif gt == GateType.CZ:
                lines.append(f"cz q[{gate.controls[0]}], q[{gate.targets[0]}];")
            elif gt == GateType.SWAP:
                lines.append(f"swap q[{gate.targets[0]}], q[{gate.targets[1]}];")
            elif gt == GateType.BARRIER:
                lines.append("barrier q;")
            elif gt == GateType.MEASURE:
                c_idx = gate.classical_target if gate.classical_target is not None else gate.targets[0]
                lines.append(f"c[{c_idx}] = measure q[{gate.targets[0]}];")
            elif gt == GateType.ORACLE:
                lines.append(f"// Oracle block: {gate.label}")

        return "\n".join(lines)


class OriginPilotTranspiler:
    """Compiles AST to Origin Quantum OS (QRunes / QPanda format)."""

    @staticmethod
    def transpile(ast: QuantumAST) -> str:
        lines = [
            "# Origin Pilot / QPanda QRunes Specification",
            "# Compiled via QMoosa-PQ Synthesis Engine",
            "import pyqpanda as pq",
            "",
            "def run_origin_pilot_circuit():",
            "    machine = pq.CPUQVM()",
            "    machine.init_qvm()",
            f"    q = machine.qAlloc_many({ast.num_qubits})",
            f"    c = machine.cAlloc_many({max(1, ast.num_clbits)})",
            "    prog = pq.QProg()",
            "",
        ]

        for gate in ast.gates:
            gt = gate.gate_type
            if gt == GateType.H:
                lines.append(f"    prog << pq.H(q[{gate.targets[0]}])")
            elif gt == GateType.X:
                lines.append(f"    prog << pq.X(q[{gate.targets[0]}])")
            elif gt == GateType.Y:
                lines.append(f"    prog << pq.Y(q[{gate.targets[0]}])")
            elif gt == GateType.Z:
                lines.append(f"    prog << pq.Z(q[{gate.targets[0]}])")
            elif gt == GateType.S:
                lines.append(f"    prog << pq.S(q[{gate.targets[0]}])")
            elif gt == GateType.T:
                lines.append(f"    prog << pq.T(q[{gate.targets[0]}])")
            elif gt == GateType.RX:
                lines.append(f"    prog << pq.RX(q[{gate.targets[0]}], {gate.params[0]:.4f})")
            elif gt == GateType.RY:
                lines.append(f"    prog << pq.RY(q[{gate.targets[0]}], {gate.params[0]:.4f})")
            elif gt == GateType.RZ:
                lines.append(f"    prog << pq.RZ(q[{gate.targets[0]}], {gate.params[0]:.4f})")
            elif gt == GateType.CX:
                lines.append(f"    prog << pq.CNOT(q[{gate.controls[0]}], q[{gate.targets[0]}])")
            elif gt == GateType.CZ:
                lines.append(f"    prog << pq.CZ(q[{gate.controls[0]}], q[{gate.targets[0]}])")
            elif gt == GateType.SWAP:
                lines.append(f"    prog << pq.SWAP(q[{gate.targets[0]}], q[{gate.targets[1]}])")
            elif gt == GateType.MEASURE:
                c_idx = gate.classical_target if gate.classical_target is not None else gate.targets[0]
                lines.append(f"    prog << pq.Measure(q[{gate.targets[0]}], c[{c_idx}])")

        lines.extend([
            "",
            "    # Run on Origin Pilot Virtual Machine",
            "    result = machine.directly_run(prog)",
            "    print('Origin Pilot Execution Result:', result)",
            "    machine.finalize()",
            "    return result",
            "",
            "if __name__ == '__main__':",
            "    run_origin_pilot_circuit()",
        ])
        return "\n".join(lines)


class IonQJSONTranspiler:
    """Compiles AST to IonQ Native Circuit JSON for direct execution on trapped-ion QPUs."""

    @staticmethod
    def transpile(ast: QuantumAST) -> str:
        import json
        gates_list = []
        for gate in ast.gates:
            gt = gate.gate_type
            if gt == GateType.H:
                gates_list.append({"gate": "h", "target": gate.targets[0]})
            elif gt == GateType.X:
                gates_list.append({"gate": "x", "target": gate.targets[0]})
            elif gt == GateType.Y:
                gates_list.append({"gate": "y", "target": gate.targets[0]})
            elif gt == GateType.Z:
                gates_list.append({"gate": "z", "target": gate.targets[0]})
            elif gt == GateType.S:
                gates_list.append({"gate": "s", "target": gate.targets[0]})
            elif gt == GateType.T:
                gates_list.append({"gate": "t", "target": gate.targets[0]})
            elif gt == GateType.RX:
                gates_list.append({"gate": "rx", "target": gate.targets[0], "rotation": gate.params[0]})
            elif gt == GateType.RY:
                gates_list.append({"gate": "ry", "target": gate.targets[0], "rotation": gate.params[0]})
            elif gt == GateType.RZ:
                gates_list.append({"gate": "rz", "target": gate.targets[0], "rotation": gate.params[0]})
            elif gt == GateType.CX:
                gates_list.append({"gate": "cnot", "control": gate.controls[0], "target": gate.targets[0]})
            elif gt == GateType.CZ:
                gates_list.append({"gate": "cz", "control": gate.controls[0], "target": gate.targets[0]})
            elif gt == GateType.SWAP:
                gates_list.append({"gate": "swap", "targets": [gate.targets[0], gate.targets[1]]})

        payload = {
            "qubits": ast.num_qubits,
            "circuit": gates_list,
        }
        return json.dumps(payload, indent=2)


class RigettiQuilTranspiler:
    """Compiles AST to Rigetti Quil 3.0 specification."""

    @staticmethod
    def transpile(ast: QuantumAST) -> str:
        lines = [
            f"DECLARE ro BIT[{max(1, ast.num_clbits)}]",
        ]
        for gate in ast.gates:
            gt = gate.gate_type
            if gt == GateType.H:
                lines.append(f"H {gate.targets[0]}")
            elif gt == GateType.X:
                lines.append(f"X {gate.targets[0]}")
            elif gt == GateType.Y:
                lines.append(f"Y {gate.targets[0]}")
            elif gt == GateType.Z:
                lines.append(f"Z {gate.targets[0]}")
            elif gt == GateType.S:
                lines.append(f"S {gate.targets[0]}")
            elif gt == GateType.T:
                lines.append(f"T {gate.targets[0]}")
            elif gt == GateType.RX:
                lines.append(f"RX({gate.params[0]:.4f}) {gate.targets[0]}")
            elif gt == GateType.RY:
                lines.append(f"RY({gate.params[0]:.4f}) {gate.targets[0]}")
            elif gt == GateType.RZ:
                lines.append(f"RZ({gate.params[0]:.4f}) {gate.targets[0]}")
            elif gt == GateType.CX:
                lines.append(f"CNOT {gate.controls[0]} {gate.targets[0]}")
            elif gt == GateType.CZ:
                lines.append(f"CZ {gate.controls[0]} {gate.targets[0]}")
            elif gt == GateType.SWAP:
                lines.append(f"SWAP {gate.targets[0]} {gate.targets[1]}")
            elif gt == GateType.MEASURE:
                c_idx = gate.classical_target if gate.classical_target is not None else gate.targets[0]
                lines.append(f"MEASURE {gate.targets[0]} ro[{c_idx}]")

        return "\n".join(lines)

